version: "3.4"

services:
  web:
    build:
      context: .
      dockerfile: dev.dockerfile
    command: ./script/start.sh
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://pguser:pgpass@db:5432/typeorm_api_development
    ports:
      - '7290:3000'
    volumes:
      - .:/usr/src/typeorm-api-base
      - /usr/src/typeorm-api-base/.build
  db:
    image: postgres:9.6.8
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: typeorm_api_development
    ports:
      - '7291:5432'
