version: 2
jobs:
  build:
    working_directory: ~/typeorm-base-api

    docker:
      - image: circleci/node:9.10.1
        environment:
          DATABASE_URL: postgres://pguser:pgpass@localhost:5432/typeorm_api_test
      - image: circleci/postgres:9.6.8-alpine
        environment:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgpass
          POSTGRES_DB: typeorm_api_test

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Run Migrations
          command: yarn db:test:prepare

      - run:
          name: Download Coverage Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Prepare Coverage Reporter
          command: ./cc-test-reporter before-build

      # run tests!
      - run: yarn test:cov

      - run:
          name: Report Coverage
          command: ./cc-test-reporter after-build --exit-code $?


