version: 2
jobs:
  build:
    working_directory: ~/typeorm-base-api

    docker:
      - image: circleci/node:9.8.0
        environment:
          DATABASE_URL: postgres://pguser:pgpass@localhost:5432/typeorm_api_test
      - image: circleci/postgres:9.6.8-alpine
        environment:
          - POSTGRES_USER: pguser
          - POSTGRES_PASSWORD: pgpass
          - POSTGRES_DB: typeorm_api_test

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Run Migrations
          command: yarn db:test:prepare

      # run tests!
      - run: yarn test:cov

      - run:
          name: Upload Coverage Results to CodeClimate
          command: yarn codeclimate-test-reporter < coverage/lcov.info


